sudo: false
dist: xenial
language: python
python:
  - "3.7.1"
install:
  - "pip install -r requirements.txt"
script:
  # The check command rebuilds all examples scons and ensures that generated
  # examples match the committed state.
  - "templatekit check"
