sudo: false
language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
script:
  # Test the examples by rebuilding them and making sure they match the
  # committed state (so that the repo is clean).
  - "scons"
  - "git diff --exit-code"
