apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.package_name }}
  labels:
    app: {{ cookiecutter.package_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ cookiecutter.package_name }}
  template:
    metadata:
      labels:
        name: {{ cookiecutter.package_name }}
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          image: "lsstsqre/{{ cookiecutter.package_name }}:latest"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: {{ cookiecutter.package_name }}
