apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: example
  template:
    metadata:
      labels:
        name: example
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          image: "lsstsqre/example:latest"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: example
